apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- name: ghcr.io/asaunders-toptal/queue
  newName: ghcr.io/asaunders-toptal/queue
  newTag: v0.0.1
