apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: ghcr.io/asaunders-toptal/queue:latest
        name: queue
        ports:
        - name: http
          containerPort: 8080
