apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: guestbook-simple
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/asaunders-toptal/backend:v0.0.1
        name: backend
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: guestbook-simple
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-simple
