apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - env: dev
        - env: staging
        - env: prod
  template:
    metadata:
      name: 'backend-{{env}}'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/asaunders-toptal/kargo-quickstart-template
        targetRevision: env/{{env}}
        path: .
      destination:
        name: in-cluster
        namespace: 'backend-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
