apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: guestbook-simple-dev
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: guestbookImage
        value: ghcr.io/asaunders-toptal/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-guestbook
        config:
          path: ./src/app/guestbook/env/dev
          images:
          - image: ${{ vars.guestbookImage }}
            tag: ${{ imageFrom(vars.guestbookImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/guestbook/env/dev
          outPath: ./out/guestbook-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for guestbook dev"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-simple-dev
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: guestbook-simple-staging
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - guestbook-simple-dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: guestbookImage
        value: ghcr.io/asaunders-toptal/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/staging
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-guestbook
        config:
          path: ./src/app/guestbook/env/staging
          images:
          - image: ${{ vars.guestbookImage }}
            tag: ${{ imageFrom(vars.guestbookImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/guestbook/env/staging
          outPath: ./out/guestbook-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for guestbook staging"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/staging
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-simple-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: guestbook-simple-prod
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - guestbook-simple-staging
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: guestbookImage
        value: ghcr.io/asaunders-toptal/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-guestbook
        config:
          path: ./src/app/guestbook/env/prod
          images:
          - image: ${{ vars.guestbookImage }}
            tag: ${{ imageFrom(vars.guestbookImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/guestbook/env/prod
          outPath: ./out/guestbook-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for guestbook prod"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/prod
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-simple-prod
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-dev
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: backend
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: backendImage
        value: ghcr.io/asaunders-toptal/backend
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-backend
        config:
          path: ./src/app/backend/env/dev
          images:
          - image: ${{ vars.backendImage }}
            tag: ${{ imageFrom(vars.backendImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/backend/env/dev
          outPath: ./out/backend-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for backend dev"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: backend-dev
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-staging
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: backend
    sources:
      stages:
      - backend-dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: backendImage
        value: ghcr.io/asaunders-toptal/backend
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/staging
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-backend
        config:
          path: ./src/app/backend/env/staging
          images:
          - image: ${{ vars.backendImage }}
            tag: ${{ imageFrom(vars.backendImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/backend/env/staging
          outPath: ./out/backend-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for backend staging"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/staging
      - uses: argocd-update
        config:
          apps:
          - name: backend-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-prod
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: backend
    sources:
      stages:
      - backend-staging
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: backendImage
        value: ghcr.io/asaunders-toptal/backend
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-backend
        config:
          path: ./src/app/backend/env/prod
          images:
          - image: ${{ vars.backendImage }}
            tag: ${{ imageFrom(vars.backendImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/backend/env/prod
          outPath: ./out/backend-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for backend prod"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/prod
      - uses: argocd-update
        config:
          apps:
          - name: backend-prod
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: queue-dev
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: queue
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: queueImage
        value: ghcr.io/asaunders-toptal/queue
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-queue
        config:
          path: ./src/app/queue/env/dev
          images:
          - image: ${{ vars.queueImage }}
            tag: ${{ imageFrom(vars.queueImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/queue/env/dev
          outPath: ./out/queue-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for queue dev"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: queue-dev
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: queue-staging
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: queue
    sources:
      stages:
      - queue-dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: queueImage
        value: ghcr.io/asaunders-toptal/queue
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/staging
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-queue
        config:
          path: ./src/app/queue/env/staging
          images:
          - image: ${{ vars.queueImage }}
            tag: ${{ imageFrom(vars.queueImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/queue/env/staging
          outPath: ./out/queue-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for queue staging"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/staging
      - uses: argocd-update
        config:
          apps:
          - name: queue-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: queue-prod
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: queue
    sources:
      stages:
      - queue-staging
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/asaunders-toptal/kargo-quickstart-template
      - name: queueImage
        value: ghcr.io/asaunders-toptal/queue
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: env/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image-queue
        config:
          path: ./src/app/queue/env/prod
          images:
          - image: ${{ vars.queueImage }}
            tag: ${{ imageFrom(vars.queueImage).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/queue/env/prod
          outPath: ./out/queue-manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: "Update images for queue prod"
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/prod
      - uses: argocd-update
        config:
          apps:
          - name: queue-prod
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
