apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: ghcr.io/asaunders-toptal/payments:latest
        name: payments
        ports:
        - name: http
          containerPort: 8080
